### ISSUE TITLE
Feature question

### ISSUE THREAD

**Issue by alturismo** [aisayev/ffmpeg-proxy#1]
Hi, im testing your approach vice vers, input a .ts stream and create a abr hls stream.

Now when i use xinetd todo so .. i have the problem at the end that the hls creation is a file like master.m3u8
and i cant output like -f mpegts -

may an idea if this would be possible ?

thanks ahead for taking a look

**Comment by aisayev** [comment]
Hi,
I think this will not work.

To use xinetd and ffmpeg stdout it should output single stream, but HLS create multiple files.

**Comment by alturismo** [comment]
ok, thanks for the info, so no chance to serve the master.m3u8 (single file) as "stream", HLS creates multiply ts files but only 1 master m3u8 file.
